1. Дана целочисленная прямоугольная матрица. Определить:
- количество строк, не содержащих ни одного нулевого элемента;
- максимальное из чисел, встречающихся в заданной матрице более одного раза.

In [43]:
import numpy as np

matrix = np.random.randint (-10, 11, (5, 5))
print(matrix)

[[  1   4   8  -6  -1]
 [  4 -10  -5  -8   9]
 [ -7  -2  -5   0   2]
 [  8  -5  -7  -9 -10]
 [ -2  -1   6  -1  -9]]


In [33]:
k = 0
for i in range(5):
    if 0 not in matrix[i, :]:
        k += 1
print(f"Количество строк без нулей: {k}")

Количество строк без нулей: 4


In [44]:
max_elem = matrix.max()
while True:
    if np.count_nonzero(matrix == max_elem) > 1:
        print(f"Максимальное из чисел в матрице, встречающееся более одного раза: {max_elem}")
        break
    else:
        max_elem -= 1

Максимальное из чисел в матрице, встречающееся более одного раза: 8
