

# Лабораторная работа 3.2. Знакомство с NumPy
Библиотека NumPy -- быстрая библиотека для математики в Python, основная структура данных -- массив `numpy.array`:

![](https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif)

In [2]:
# подключение модуля numpy под именем np
import numpy as np

In [3]:
# основная структура данных - массив
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

print("a =", a)
print("b =", b)

a = [1 2 3 4 5]
b = [0.1 0.2 0.3 0.4 0.5]


Создайте массив с 5 любыми числами:

In [7]:
arr = np.random.randint(-6, 6, 5)
arr

array([-5, -2,  4,  0, -1])

Арифметические операции, в отличие от операций над списками, применяются поэлементно:

In [8]:
list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

print("list1:", list1)
print('\tlist1 * 3:', list1 * 3)
print('\tlist1 + [1]:', list1 + [1])

print('array1:', array1)
print('\tarray1 * 3:', array1 * 3)
print('\tarray1 + 1:', array1 + 1)

list1: [1, 2, 3]
	list1 * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
	list1 + [1]: [1, 2, 3, 1]
array1: [1 2 3]
	array1 * 3: [3 6 9]
	array1 + 1: [2 3 4]


Создайте массив из 5 чисел. Возведите каждый элемент массива в степень 3

In [18]:
arr = np.random.randint(-6, 6, 5)
print(arr)
arr ** 3

[-6  3  0 -5 -5]


array([-216,   27,    0, -125, -125], dtype=int32)

Если в операции участвуют $2$ массива (по умолчанию -- одинакового размера), операции считаются для соответствующих пар:

In [19]:
print("a + b =", a + b)
print("a * b =", a * b)

a + b = [1.1 2.2 3.3 4.4 5.5]
a * b = [0.1 0.4 0.9 1.6 2.5]


In [20]:
# вот это разность
print("a - b =", a - b)

# вот это деление
print("a / b =", a / b)

# вот это целочисленное деление
print("a // b =", a // b)

# вот это квадрат
print("a ** 2 =", a ** 2)

a - b = [0.9 1.8 2.7 3.6 4.5]
a / b = [10. 10. 10. 10. 10.]
a // b = [ 9.  9. 10.  9. 10.]
a ** 2 = [ 1  4  9 16 25]


 Создайте два массива одинаковой длины. Выведите массив, полученный делением одного массива на другой.

In [37]:
arr_1 = np.random.randint(-6, 6, 5)
arr_2 = np.random.randint(-6, 6, 5)
result = arr_1 // arr_2
print(result)

[ 0  5 -1 -1  4]


#### *Л — логика*
К элементам массива можно применять логические операции.

Возвращаемое значение -- массив, содержащий результаты вычислений для каждого элемента (`True` -- "да" или `False` -- "нет"):

In [38]:
print("a =", a)
print("\ta > 1: ", a > 1)
print("\nb =", b)
print("\tb < 0.5:  ", b < 0.5)

print("\nОдновременная проверка условий:")
print("\t(a > 1) & (b < 0.5):  ", (a>1) & (b < 0.5))
print("А вот это проверяет, что a > 1 ИЛИ b < 0.5:  ", (a > 1) | (b < 0.5))

a = [1 2 3 4 5]
	a > 1:  [False  True  True  True  True]

b = [0.1 0.2 0.3 0.4 0.5]
	b < 0.5:   [ True  True  True  True False]

Одновременная проверка условий:
	(a > 1) & (b < 0.5):   [False  True  True  True False]
А вот это проверяет, что a > 1 ИЛИ b < 0.5:   [ True  True  True  True  True]


Создайте 2 массива из 5 элементов. Проверьте условие "Элементы первого массива меньше 6, элементы второго массива делятся на 3"

In [39]:
arr_1 = np.random.randint(-10, 10, 5)
arr_2 = np.random.randint(-10, 10, 5)
print(arr_1 < 6)
print(arr_2 % 3 == 0)

[ True False  True  True  True]
[ True  True  True False False]


Теперь проверьте условие "Элементы первого массива делятся на 2 или элементы второго массива больше 2"

In [59]:
print((arr_1 % 2 == 0) | (arr_2 > 2))

[ True  True  True  True  True]


Зачем это нужно? Чтобы выбирать элементы массива, удовлетворяющие какому-нибудь условию:

In [60]:
print("a =", a)
print("a > 2:", a > 2)
# индексация - выбираем элементы из массива в тех позициях, где True
print("a[a > 2]:", a[a > 2])

a = [1 2 3 4 5]
a > 2: [False False  True  True  True]
a[a > 2]: [3 4 5]


Создайте массив с элементами от 1 до 20. Выведите все элементы, которые больше 5 и не делятся на 2

Подсказка: создать массив можно с помощью функции np.arange(), действие которой аналогично функции range, которую вы уже знаете.

In [62]:
arr = np.arange(1,21)
print(arr[(arr > 5) & (arr % 2 != 0)])

[ 7  9 11 13 15 17 19]


#### А ещё NumPy умеет...

Все операции NumPy оптимизированы для быстрых вычислений над целыми массивами чисел и в методах `np.array` реализовано множество функций, которые могут вам понадобиться:

In [63]:
# теперь можно считать средний размер котиков в одну строку!
print("np.mean(a) =", np.mean(a))
# минимальный элемент
print("np.min(a) =", np.min(a))
# индекс минимального элемента
print("np.argmin(a) =", np.argmin(a))
# вывести значения массива без дубликатов
print("np.unique(['male', 'male', 'female', 'female', 'male']) =", np.unique(['male', 'male', 'female', 'female', 'male']))

# и ещё много всяких методов
# Google в помощь

np.mean(a) = 3.0
np.min(a) = 1
np.argmin(a) = 0
np.unique(['male', 'male', 'female', 'female', 'male']) = ['female' 'male']


---

---

Пора еще немного потренироваться с NumPy.

Выполните операции, перечисленные ниже:

In [64]:
print("Разность между a и b:", a - b
     )
print("Квадраты элементов b:", b ** 2
     )
print("Половины произведений элементов массивов a и b:", a * b
     )

print()
print("Максимальный элемент b:", np.max(b)
     )
print("Сумма элементов массива b:", np.sum(b)
     )
print("Индекс максимального элемента b:", np.argmax(b)
     )

Разность между a и b: [0.9 1.8 2.7 3.6 4.5]
Квадраты элементов b: [0.01 0.04 0.09 0.16 0.25]
Половины произведений элементов массивов a и b: [0.1 0.4 0.9 1.6 2.5]

Максимальный элемент b: 0.5
Сумма элементов массива b: 1.5
Индекс максимального элемента b: 4


 Задайте два массива: [5, 2, 3, 12, 4, 5]   и   ['f', 'o', 'o', 'b', 'a', 'r']

Выведите буквы из второго массива, индексы которых соответствуют индексам чисел из первого массива, которые больше 1, меньше 5 и делятся на 2

In [65]:
arr_1 = np.array([5, 2, 3, 12, 4, 5])
arr_2 = np.array(['f', 'o', 'o', 'b', 'a', 'r'])
arr_2[np.where ((arr_1 > 1) & (arr_1 < 5) & (arr_1 % 2 == 0))]

array(['o', 'a'], dtype='<U1')