# Лабораторная работа 3.2. Домашнее задание

### Задание №1

Создайте два массива: в первом должны быть четные числа от 2 до 12 включительно, а в другом числа 7, 11, 15, 18, 23, 29.

$1.$ Сложите массивы и возведите элементы получившегося массива в квадрат:

In [2]:
import numpy as np

arr_1 = np.arange(1,7) * 2
arr_2 = np.array([7, 11, 15, 18, 23, 29])
print((arr_1 + arr_2) ** 2)

[  81  225  441  676 1089 1681]


$2.$ Выведите все элементы из первого массива, индексы которых соответствуют индексам тех элементов второго массива, которые больше 12 и дают остаток 3 при делении на 5.

In [4]:
arr_1[np.where ((arr_2 > 12) & (arr_2 % 5 == 3))]

array([ 8, 10])

*3.* Проверьте условие "Элементы первого массива делятся на 4, элементы второго массива меньше 14". (Подсказка: в результате должен получиться массив с True и False)

In [6]:
(arr_1 % 4 == 0) & (arr_2 < 14)

array([False,  True, False, False, False, False])

### Задание №2

* Найдите интересный для вас датасет. Например, можно выбрать датасет тут. http://data.un.org/Explorer.aspx (выбираете датасет, жмете на view data, потом download, выбирайте csv формат)
* Рассчитайте подходящие описательные статистики для признаков объектов в выбранном датасете
* Проанализируйте и прокомментируйте содержательно получившиеся результаты
* Все комментарии оформляйте строго в ячейках формата markdown
    

In [8]:
import csv
import numpy as np
with open('topSubscribed.csv', 'r', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile, delimiter=';')
    views = []
    video = []
    next(reader)
    for i in reader:
        views.append(int(i[3]))
        video.append(int(i[4]))
    arr_views = np.array(views)
    arr_video = np.array(video)
    print(f"Среднее количество просмотров: {np.mean(arr_views)}") 
    print(f"Среднее количество видео: {np.mean(arr_video)}" )
    
    print(f"Среднее отклонение количества просмотров {np.std(arr_views)}") 
    print(f"Среднее отклонение количества видео: {np.std(arr_video)}")
    
    print(f"Дисперсия количества просмотров {np.var(arr_views)}") 
    print(f"Дисперсия количества видео: {np.var(arr_video)}" )

Среднее количество просмотров: 9994912409.734
Среднее количество видео: 8536.892
Среднее отклонение количества просмотров 12998953101.280153
Среднее отклонение количества видео: 30775.865282300936
Дисперсия количества просмотров 1.6897278172928092e+20
Дисперсия количества видео: 947153883.874336
